name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install dependencies
        run: mvn install --no-transfer-progress

      - name: Run Linter
        run: mvn spotless:check

      - name: Run backend tests
        run: mvn test --no-transfer-progress

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run frontend linter
        run: npm run lint

      - name: Run frontend tests
        run: npm test -- --coverage
