name: Security Scans

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r backend/requirements.txt bandit safety
      - name: Run Bandit
        run: bandit -r backend/
      - name: Run Safety
        run: safety check -r backend/requirements.txt

  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Run npm audit
        run: cd frontend && npm audit --audit-level=high

  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Trivy
        run: sudo apt-get install -y trivy
      - name: Build Docker image
        run: docker build -t my-backend ./backend
      - name: Scan Docker image
        run: trivy image my-backend 